---
# tasks file for sample-mysql

- name: Create partitionon /dev/sdb
  parted:
    device: /dev/sdb
    number: 1
    state: present
    part_end: 800MB

- name: Create an LVM volume group
  lvg:
    vg: vg_database
    pvs: /dev/sdb1

- name: Create an LVM logical volume of 512MB
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: 512m

- name: Create XFS filesystem on lv_mysql
  filesystem:
    fstype: xfs
    dev: /dev/vg_database/lv_mysql

- name: Create directory /mnt/mysql_backups if not exist
  file:
    path: /mnt/mysql_backups
    state: directory

- name: lv_mysql is permanetly mounted on /mnt/mysql_backups
  mount:
    path: /mnt/mysql_backups
    src: /dev/vg_database/lv_mysql
    fstype: xfs
    state: present

- name: install mysql-community- server package
  yum:
    name: mysql-community-server
    state: latest

- name: Make sure firewall service is running
  service:
    name: firewalld
    state: started
    enabled: yes

- name: configure firewall to allow all traffic on port 3306
  firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled

- name: Start MySQL server and enable
  service:
    name: mysqld
    state: started
    enabled: yes

- name: MySQL server configuration
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644 

- name: set MySQL root user password
  mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    login_password: ''
    name: 'root'
    host_all: yes
    password: "{{ database_password }}"
    check_implicit_admin: yes
