---
- hosts: all
  tasks:
    - name: set banner to /etc/motd
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        line: banner /etc/motd

    - name: Disable X11Forwarding
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'X11Forwarding.*'
        line: X11Forwarding no

    - name: Set MaxAuthTries to 3
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '.*MaxAuthTries.*'
        line: MaxAuthTries 3
