---
- hosts: all
  become: yes

  tasks:

    - name: Set vm.swappiness to 10 if srever RAM larger than 2048MB
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present
      when: ansible_memory_mb.real.total > 2048

    - name: Prints a message if server RAM smaller than 2048MB
      debug:
        msg: Server memory less than 2048MB
      when: ansible_memory_mb.real.total < 2048

