---
- hosts: webservers
  become: yes

  tasks:

    - name: Set the default boot target to multi-user
      file:
        src: /usr/lib/systemd/system/multi-user.target
        dest: /etc/systemd/system/default.target
        state: link
